/// low-level access to the Windows Uniscribe API
// - this unit is a part of the Open Source Synopse mORMot framework 2,
// licensed under a MPL/GPL/LGPL three license - see LICENSE.md
unit mormot.lib.uniscribe;


{
  *****************************************************************************

   Uniscribe typography and complex scripts processing Windows API
   - UniScribe Shared Types
   - UniScribe API Functions
   - FontSub API for font sunset embedding
   - GDI Font Services: IFontProvider, IFontEnumerator and IFontDC
   - Uniscribe Shaper and FontSub Subsetter: IFontShaper and IFontSubsetter

  *****************************************************************************

}

interface

{$I ..\mormot.defines.inc}

{$ifdef OSPOSIX}

// do-nothing-unit on non Windows system

implementation

{$else}

uses
  windows,
  sysutils,
  mormot.core.base,
  mormot.core.os,
  mormot.core.unicode,
  mormot.lib.core;


{ ****************** UniScribe Shared Types }

const
  /// the Uniscribe API library name
  Usp10 = 'usp10.dll';

  /// error returned by Uniscribe when the current selected font
  // does not contain sufficient glyphs or shaping tables
  USP_E_SCRIPT_NOT_IN_FONT =
    HRESULT((SEVERITY_ERROR shl 31) or (FACILITY_ITF shl 16)) or $200;

type
  /// UniScribe script state flag elements
  // - r0,r1,r2,r3,r4: map TScriptState.uBidiLevel bits (not real flags)
  // - fOverrideDirection: Set when in LRO/RLO embedding
  // - fInhibitSymSwap: Set by U+206A (ISS), cleared by U+206B (ASS)
  // - fCharShape: Set by U+206D (AAFS), cleared by U+206C (IAFS)
  // - fDigitSubstitute: Set by U+206E (NADS), cleared by U+206F (NODS)
  // - fInhibitLigate: Equiv !GCP_Ligate, no Unicode control chars yet
  // - fDisplayZWG: Equiv GCP_DisplayZWG, no Unicode control characters yet
  // - fArabicNumContext: For EN->AN Unicode rule
  // - fGcpClusters: For Generating Backward Compatible GCP Clusters (legacy Apps)
  TScriptState_enum = (
    r0, r1, r2, r3, r4,
    fOverrideDirection,
    fInhibitSymSwap,
    fCharShape,
    fDigitSubstitute,
    fInhibitLigate,
    fDisplayZWG,
    fArabicNumContext,
    fGcpClusters
  );

  /// a set of UniScribe script state flags
  TScriptState_set = set of TScriptState_enum;

  PScriptState = ^TScriptState;

  /// an UniScribe script state
  // - uBidiLevel: Unicode Bidi algorithm embedding level (0..16)
  // - fFlags: Script state flags
  TScriptState = packed record
   case Byte of
      0: (
        uBidiLevel: Byte {:5}
      );
      1: (
        fFlags: TScriptState_set
      )
  end;

  /// Uniscribe script analysis flag elements
  // - s0,s1,s2,s3,s4,s5,s6,s7,s8,s9: map TScriptAnalysis.eScript bits
  // - fRtl: Rendering direction - set for Right To Left scripting
  // - fLayoutRtl: Set for GCP classes ARABIC/HEBREW and LOCALNUMBER
  // - fLinkBefore: Implies there was a ZWJ before this item
  // - fLinkAfter: Implies there is a ZWJ following this item.
  // - fLogicalOrder: Set by client as input to ScriptShape/Place
  // - fNoGlyphIndex: Generated by ScriptShape/Place - this item does not use
  // glyph indices
  TScriptAnalysis_enum = (
    s0, s1, s2, s3, s4, s5, s6, s7, s8, s9,
    fRtl,
    fLayoutRtl,
    fLinkBefore,
    fLinkAfter,
    fLogicalOrder,
    fNoGlyphIndex
  );

  /// a set of Uniscribe script analysis flags
  TScriptAnalysis_set = set of TScriptAnalysis_enum;

  /// an Uniscribe script analysis
  // - eScript:  Shaping engine
  // - fFlags: Script analysis flags
  // - s: Script state
  TScriptAnalysis = packed record
   case Byte of
      0: (
        eScript: Word
      );
      1: (
        fFlags: TScriptAnalysis_set;
        s: TScriptState
      );
  end;
  PScriptAnalysis = ^TScriptAnalysis;

  /// a Uniscribe script item, after analysis of a unicode text
  TScriptItem = packed record
    /// Logical offset to first character in this item
    iCharPos: integer;
    /// corresponding Uniscribe script analysis
    a: TScriptAnalysis;
  end;
  PScriptItem = ^TScriptItem;

  /// all possible Uniscribe processing properties of a given language
  // - fNumeric:  if a script contains only digits
  // - fComplex: Script requires special shaping or layout
  // - fNeedsWordBreaking: Requires ScriptBreak for word breaking information
  // - fNeedsCaretInfo: Requires caret restriction to cluster boundaries
  // - bCharSet0 .. bCharSet7: Charset to use when creating font
  // - fControl: Contains only control characters
  // - fPrivateUseArea: This item is from the Unicode range U+E000 through U+F8FF
  // - fNeedsCharacterJustify: Requires inter-character justification
  // - fInvalidGlyph: Invalid combinations generate glyph wgInvalid in the glyph buffer
  // - fInvalidLogAttr: Invalid combinations are marked by fInvalid in the logical attributes
  // - fCDM: Contains Combining Diacritical Marks
  // - fAmbiguousCharSet: Script does not correspond 1// :1 with a charset
  // - fClusterSizeVaries: Measured cluster width depends on adjacent clusters
  // - fRejectInvalid: Invalid combinations should be rejected
  TScriptProperties_enum = (
    fNumeric,
    fComplex,
    fNeedsWordBreaking,
    fNeedsCaretInfo,
    bCharSet0, bCharSet1, bCharSet2, bCharSet3, bCharSet4, bCharSet5,
    bCharSet6, bCharSet7,
    fControl,
    fPrivateUseArea,
    fNeedsCharacterJustify,
    fInvalidGlyph,
    fInvalidLogAttr,
    fCDM,
    fAmbiguousCharSet,
    fClusterSizeVaries,
    fRejectInvalid
  );

  /// set of possible Uniscribe processing properties of a given language
  TScriptProperties_set = set of TScriptProperties_enum;
  PScriptProperties = ^TScriptProperties;

  /// Contains information about Uniscribe special processing for each script
  TScriptProperties = packed record
    /// Primary and sublanguage associated with script
    langid: Word;
    /// set of possible Uniscribe processing properties for a given language
    fFlags: TScriptProperties_set;
  end;

  /// an array of Uniscribe processing information
  PScriptPropertiesArray = ^TPScriptPropertiesArray;
  TPScriptPropertiesArray = array[byte] of PScriptProperties;

  /// Uniscribe visual (glyph) attributes
  // - a0 .. a3: map the Justification class number bits
  // - fClusterStart: First glyph of representation of cluster
  // - fDiacritic: Diacritic
  // - fZeroWidth: Blank, ZWJ, ZWNJ etc, with no width
  // - fReserved: General reserved bit
  TScriptVisAttr_enum = (
    a0, a1, a2, a3,
    fClusterStart,     {:1}  // First glyph of representation of cluster
    fDiacritic,        {:1}  // Diacritic
    fZeroWidth,        {:1}  // Blank, ZWJ, ZWNJ etc, with no width
    fReserved          {:1}  // General reserved
  );
  /// set of Uniscribe visual (glyph) attributes
  TScriptVisAttr_set = set of TScriptVisAttr_enum;

  /// Contains the visual (glyph) attributes that identify clusters and
  // justification points, as generated by ScriptShape
  // - uJustification: Justification class bits
  // - fFlags: Uniscribe visual (glyph) attributes
  // - fShapeReserved: Reserved for use by shaping engines
  TScriptVisAttr = packed record
   case Byte of
    0: (
      uJustification: Byte {:4}
    );
    1: (
      fFlags: TScriptVisAttr_set;
      fShapeReserved: Byte {:8}
    );
  end;
  PScriptVisAttr = ^TScriptVisAttr;

  TScriptControlAttr_enum = (
    fContextDigits,
    fInvertPreBoundDir,
    fInvertPostBoundDir,
    fLinkStringBefore,
    fLinkStringAfter,
    fNeutralOverride,
    fNumericOverride,
    fLegacyBidiClass,
    fScr0, fScr1, fScr2, fScr3, fScr4, fScr5, fScr6, fScr7);

  TScriptControlAttr_set = set of TScriptControlAttr_enum;

  TScriptControl = packed record
    uDefaultLanguage: Word;
    fFlags: TScriptControlAttr_set;
  end;
  PScriptControl = ^TScriptControl;


{ ****************** UniScribe API Functions }

/// Uniscribe function to break a Unicode string into individually shapeable items
// - pwcInChars: Pointer to a Unicode string to itemize.
// - cInChars: Number of characters in pwcInChars to itemize.
// - cMaxItems: Maximum number of SCRIPT_ITEM structures defining items to process.
// - psControl: Optional. Pointer to a SCRIPT_CONTROL structure indicating the
// type of itemization to perform. Alternatively, the application can set this
// parameter to NULL if no SCRIPT_CONTROL properties are needed.
// - psState: Optional. Pointer to a SCRIPT_STATE structure indicating
// the initial bidirectional algorithm state. Alternatively, the application
// can set this parameter to NULL if the script state is not needed.
// - pItems: Pointer to a buffer in which the function retrieves SCRIPT_ITEM
// structures representing the items that have been processed. The buffer
// should be cMaxItems*sizeof(SCRIPT_ITEM) + 1 bytes in length. It is invalid
// to call this function with a buffer to hold less than two SCRIPT_ITEM
// structures. The function always adds a terminal item to the item analysis
// array so that the length of the item with zero-based index "i" is
// always available as:
// ! pItems[i+1].iCharPos - pItems[i].iCharPos;
// - pcItems: Pointer to the number of SCRIPT_ITEM structures processed
function ScriptItemize(
    const pwcInChars: PWideChar; cInChars: integer; cMaxItems: integer;
    const psControl: pointer; const psState: pointer;
    pItems: PScriptItem; var pcItems: integer): HRESULT;
  stdcall; external Usp10;

/// Uniscribe function to retrieve information about the current scripts
// - ppSp: Pointer to an array of pointers to SCRIPT_PROPERTIES structures
// indexed by script.
// - piNumScripts: Pointer to the number of scripts. The valid range for this
// value is 0 through piNumScripts-1.
function ScriptGetProperties(out ppSp: PScriptPropertiesArray;
  out piNumScripts: integer): HRESULT;
  stdcall; external Usp10;

/// Uniscribe function to convert an array of run embedding levels to a map
// of visual-to-logical position and/or logical-to-visual position
// - cRuns: Number of runs to process
// - pbLevel: Array of run embedding levels
// - piVisualToLogical: List of run indices in visual order
// - piLogicalToVisual: List of visual run positions
function ScriptLayout(cRuns: integer; const pbLevel: PByte;
    piVisualToLogical: PInteger; piLogicalToVisual: PInteger): HRESULT;
  stdcall; external Usp10;

/// Uniscribe function to generate glyphs and visual attributes for an Unicode run
// - hdc: Optional (see under caching)
// - psc: Uniscribe font metric cache handle
// - pwcChars: Logical unicode run
// - cChars: Length of unicode run
// - cMaxGlyphs: Max glyphs to generate
// - psa: Result of ScriptItemize (may have fNoGlyphIndex set)
// - pwOutGlyphs: Output glyph buffer
// - pwLogClust: Logical clusters
// - psva: Visual glyph attributes
// - pcGlyphs: Count of glyphs generated
function ScriptShape(hdc: HDC; var psc: pointer; const pwcChars: PWideChar;
    cChars: integer; cMaxGlyphs: integer; psa: PScriptAnalysis;
    pwOutGlyphs: PWord; pwLogClust: PWord; psva: PScriptVisAttr;
    var pcGlyphs: integer): HRESULT;
  stdcall; external Usp10;

/// Uniscribe function to apply the specified digit substitution settings
// to the specified script control and script state structures
function ScriptApplyDigitSubstitution(
    const psds: pointer; const psControl: pointer;
    const psState: pointer): HRESULT;
  stdcall; external Usp10;

/// Uniscribe function to release a font metric cache filled by ScriptShape
function ScriptFreeCache(var psc: pointer): HRESULT;
  stdcall; external Usp10;


{ ****************** FontSub API for font sunset embedding }

const
  /// CreateFontPackage() usFlags: make a subset
  TTFCFP_FLAGS_SUBSET = 1;
  /// CreateFontPackage() usFlags: the source is a .ttc collection
  TTFCFP_FLAGS_TTC = 4;
  /// CreateFontPackage() usFlags: the keep list holds glyph indexes, not
  // code points - glyphs of shaped text have no code point of their own
  TTFCFP_FLAGS_GLYPHLIST = 8;
  /// CreateFontPackage() usSubsetFormat: a subset keeping the glyph indexes
  TTFMFP_SUBSET = 0;
  /// CreateFontPackage() usSubsetPlatform: Microsoft
  TTFCFP_MS_PLATFORMID = 3;
  /// CreateFontPackage() usSubsetEncoding: any
  TTFCFP_DONT_CARE = 65535;
  /// GetFontData() table tag of a whole .ttc collection: 'ttcf'
  TTCF_TABLE = $66637474;

var
  /// font subset embedding using Windows XP CreateFontPackage() FontSub.dll
  // - see http://msdn.microsoft.com/en-us/library/dd183502
  // - you should first call HasCreateFontPackage to resolve this API dynamically
  CreateFontPackage: function(puchSrcBuffer: pointer; ulSrcBufferSize: cardinal;
    var puchFontPackageBuffer: PAnsiChar; var pulFontPackageBufferSize: cardinal;
    var pulBytesWritten: cardinal; usFlags, usTTCIndex, usSubsetFormat,
    usSubsetLanguage, usSubsetPlatform, usSubsetEncoding: word;
    pusSubsetKeepList: pointer; usSubsetKeepListCount: word;
    lpfnAllocate, lpfnReAllocate, lpfnFree, reserved: pointer): cardinal; cdecl;

/// resolve CreateFontPackage() API call from FontSub.dll
function HasCreateFontPackage: boolean;

// some low-level functions compatible with lpfnAllocate,lpfnReAllocate,lpfnFree
// parameters of CreateFontPackage()
function lpfnAllocate(Size: integer): pointer; cdecl;
function lpfnReAllocate(Buffer: pointer; Size: integer): pointer; cdecl;
procedure lpfnFree(Buffer: pointer); cdecl;


{ ****************** GDI Font Services: IFontProvider, IFontEnumerator and IFontDC }

type
  /// Windows GDI implementation of IFontProvider
  // - each TFontHandle is a HFONT, each TFontDC a HDC
  TGdiFontProvider = class(TInterfacedObject, IFontProvider)
  public
    function CreateFont(const Request: TFontRequest): TFontHandle;
    procedure DeleteFont(Font: TFontHandle);
    function SelectFont(DC: TFontDC; Font: TFontHandle): TFontHandle;
    function GetTextMetrics(DC: TFontDC; out Metrics: TFontMetrics): boolean;
    function GetOutlineMetrics(DC: TFontDC;
      out Metrics: TFontOutlineMetrics): boolean;
    function GetCharAbcWidths(DC: TFontDC; FirstChar, LastChar: cardinal;
      out Widths: TFontCharAbcArray): boolean;
    function GetFontData(DC: TFontDC; TableTag, Offset: cardinal;
      Buffer: pointer; BufferSize: cardinal): cardinal;
    function FontDataError: cardinal;
    function GetFaceFile(DC: TFontDC; out Face: RawByteString): boolean;
  end;

  /// Windows GDI implementation of IFontEnumerator
  TGdiFontEnumerator = class(TInterfacedObject, IFontEnumerator)
  public
    procedure EnumTrueTypeFonts(DC: TFontDC; var List: TRawUtf8DynArray);
  end;

  /// Windows GDI implementation of IFontDC - transitional, as IFontDC
  TGdiFontDC = class(TInterfacedObject, IFontDC)
  public
    function CreateDC: TFontDC;
    procedure DeleteDC(DC: TFontDC);
    function GetScreenLogPixels(DC: TFontDC): integer;
  end;


{ ****************** Uniscribe Shaper and FontSub Subsetter: IFontShaper and IFontSubsetter }

type
  /// Uniscribe implementation of IFontShaper
  // - returns false when no item of the text is complex or right-to-left
  // - otherwise one run per item, in visual order (ScriptLayout); ScriptShape
  // runs without a DC first, with one on E_PENDING or USP_E_SCRIPT_NOT_IN_FONT
  // - an item ScriptShape fails on is fskPlain + fsoFailed after E_OUTOFMEMORY
  // or a failed retry, fskSkip + fsoFailed after any other error, and an item
  // shaped to no glyph at all is fskSkip + fsoDone
  // - zero-width glyphs which are no diacritic are left out; Advances and
  // Offsets stay empty, the advances of the font apply
  TUniscribeShaper = class(TInterfacedObject, IFontShaper)
  public
    function Shape(Text: PWideChar; Len: integer; Font: TFontHandle;
      RightToLeft: boolean; out Runs: TFontShapedRuns): boolean;
  end;

  /// FontSub implementation of IFontSubsetter, through CreateFontPackage
  // - keeps glyph indexes (TTFCFP_FLAGS_GLYPHLIST): Request.Unicodes are
  // resolved through the cmap of Font with GetGlyphIndicesW, so Font is needed
  // - a face of a .ttc collection is subset from the whole collection, at the
  // index of its table directory in the collection header (TtcFaceIndex)
  TFontSubSubsetter = class(TInterfacedObject, IFontSubsetter)
  public
    function Subset(const Face: RawByteString; const Request: TFontSubsetRequest;
      Font: TFontHandle; out Output: RawByteString): boolean;
    function SupportsSymbolic: boolean;
  end;

/// keep only the tables a PDF needs of a CreateFontPackage subset
procedure ReduceTtf(out Ttf: RawByteString; SubsetData: pointer;
  SubsetSize: integer);


implementation


{ ****************** FontSub API for font sunset embedding }

function lpfnAllocate(Size: integer): pointer; cdecl;
begin
  GetMem(result, Size);
end;

function lpfnReAllocate(Buffer: pointer; Size: integer): pointer; cdecl;
begin
  ReallocMem(Buffer, Size);
  result := Buffer;
end;

procedure lpfnFree(Buffer: pointer); cdecl;
begin
  FreeMem(Buffer);
end;

var
  FontSub: THandle = INVALID_HANDLE_VALUE;

function HasCreateFontPackage: boolean;
begin
  if FontSub = INVALID_HANDLE_VALUE then
  begin
    FontSub := SafeLoadLibrary('FontSub.dll');
    if FontSub <> 0 then
      CreateFontPackage := LibraryResolve(FontSub, 'CreateFontPackage');
  end;
  result := Assigned(@CreateFontPackage);
end;


{ ****************** GDI Font Services: IFontProvider, IFontEnumerator and IFontDC }

{ TGdiFontProvider }

function TGdiFontProvider.CreateFont(const Request: TFontRequest): TFontHandle;
var
  lf: TLogFontW;
begin
  FillChar(lf, SizeOf(lf), 0);
  lf.lfHeight    := Request.Height;
  lf.lfWeight    := Request.Weight;
  lf.lfItalic    := Request.Italic;
  lf.lfCharSet   := Request.CharSet;
  lf.lfPitchAndFamily := Request.PitchAndFamily;
  lf.lfOutPrecision   := OUT_TT_ONLY_PRECIS;
  lf.lfClipPrecision  := CLIP_DEFAULT_PRECIS;
  lf.lfQuality        := DEFAULT_QUALITY;
  if Request.FaceName <> '' then
    Move(Request.FaceName[1], lf.lfFaceName[0],
      MinPtrInt(Length(Request.FaceName), LF_FACESIZE - 1) * SizeOf(WideChar));
  result := TFontHandle(CreateFontIndirectW(lf));
end;

procedure TGdiFontProvider.DeleteFont(Font: TFontHandle);
begin
  if Font <> nil then
    DeleteObject(HGDIOBJ(Font));
end;

function TGdiFontProvider.SelectFont(DC: TFontDC; Font: TFontHandle): TFontHandle;
begin
  result := TFontHandle(SelectObject(HDC(DC), HGDIOBJ(Font)));
end;

function TGdiFontProvider.GetTextMetrics(DC: TFontDC;
  out Metrics: TFontMetrics): boolean;
var
  tm: TTextMetric;
begin
  result := Windows.GetTextMetrics(HDC(DC), tm);
  if result then
  begin
    Metrics.tmHeight          := tm.tmHeight;
    Metrics.tmAscent          := tm.tmAscent;
    Metrics.tmDescent         := tm.tmDescent;
    Metrics.tmInternalLeading := tm.tmInternalLeading;
    Metrics.tmExternalLeading := tm.tmExternalLeading;
    Metrics.tmAveCharWidth    := tm.tmAveCharWidth;
    Metrics.tmMaxCharWidth    := tm.tmMaxCharWidth;
    Metrics.tmWeight          := tm.tmWeight;
    Metrics.tmOverhang        := tm.tmOverhang;
    Metrics.tmFirstChar       := WideChar(tm.tmFirstChar);
    Metrics.tmLastChar        := WideChar(tm.tmLastChar);
    Metrics.tmDefaultChar     := WideChar(tm.tmDefaultChar);
    Metrics.tmBreakChar       := WideChar(tm.tmBreakChar);
    Metrics.tmItalic          := tm.tmItalic;
    Metrics.tmCharSet         := tm.tmCharSet;
    Metrics.tmPitchAndFamily  := tm.tmPitchAndFamily;
  end;
end;

function TGdiFontProvider.GetOutlineMetrics(DC: TFontDC;
  out Metrics: TFontOutlineMetrics): boolean;
var
  otm: TOutlineTextmetric;
begin
  FillChar(otm, SizeOf(otm), 0);
  otm.otmSize := SizeOf(otm);
  result := Windows.GetOutlineTextMetrics(HDC(DC), SizeOf(otm), @otm) <> 0;
  if result then
  begin
    Metrics.otmSize              := otm.otmSize;
    Metrics.otmAscent            := otm.otmAscent;
    Metrics.otmDescent           := otm.otmDescent;
    Metrics.otmLineGap           := otm.otmLineGap;
    Metrics.otmItalicAngle       := otm.otmItalicAngle;
    Metrics.otmrcFontBox.Left    := otm.otmrcFontBox.Left;
    Metrics.otmrcFontBox.Top     := otm.otmrcFontBox.Top;
    Metrics.otmrcFontBox.Right   := otm.otmrcFontBox.Right;
    Metrics.otmrcFontBox.Bottom  := otm.otmrcFontBox.Bottom;
    Metrics.otmMacAscent         := otm.otmMacAscent;
    Metrics.otmMacDescent        := otm.otmMacDescent;
    Metrics.otmMacLineGap        := otm.otmMacLineGap;
    Metrics.otmEMSquare          := otm.otmEMSquare;
    Metrics.otmCapEmHeight       := otm.otmsCapEmHeight;
    Metrics.otmXHeight           := otm.otmsXHeight;
    Metrics.otmStrikeoutPosition := otm.otmsStrikeoutPosition;
    Metrics.otmStrikeoutSize     := otm.otmsStrikeoutSize;
    Metrics.otmUnderscorePosition := otm.otmsUnderscorePosition;
    Metrics.otmUnderscoreSize    := otm.otmsUnderscoreSize;
  end;
end;

function TGdiFontProvider.GetCharAbcWidths(DC: TFontDC;
  FirstChar, LastChar: cardinal; out Widths: TFontCharAbcArray): boolean;
var
  n: integer;
  W: array of TABC;
  i: integer;
begin
  n := integer(LastChar) - integer(FirstChar) + 1;
  if n <= 0 then
  begin
    result := false;
    exit;
  end;
  SetLength(W, n);
  // the ANSI call maps the bytes through the charset of the selected font: with
  // ANSI_CHARSET, as the PDF engine creates its fonts, 128..159 resolve to their
  // WinAnsi characters, as the IFontProvider contract requires
  result := GetCharABCWidthsA(HDC(DC), FirstChar, LastChar, W[0]);
  if result then
  begin
    SetLength(Widths, n);
    for i := 0 to n - 1 do
    begin
      Widths[i].abcA := W[i].abcA;
      Widths[i].abcB := W[i].abcB;
      Widths[i].abcC := W[i].abcC;
    end;
  end;
end;

function TGdiFontProvider.GetFontData(DC: TFontDC; TableTag, Offset: cardinal;
  Buffer: pointer; BufferSize: cardinal): cardinal;
begin
  result := Windows.GetFontData(HDC(DC), TableTag, Offset, Buffer, BufferSize);
end;

function TGdiFontProvider.FontDataError: cardinal;
begin
  result := GDI_ERROR;
end;

function ReadFontData(dc: HDC; Tag: cardinal; out Data: RawByteString): boolean;
var
  size: cardinal;
begin
  result := false;
  size := Windows.GetFontData(dc, Tag, 0, nil, 0);
  if (size = GDI_ERROR) or
     (size = 0) then
    exit;
  FastSetRawByteString(Data, nil, size);
  result := Windows.GetFontData(dc, Tag, 0, pointer(Data), size) = size;
  if not result then
    Data := '';
end;

function TGdiFontProvider.GetFaceFile(DC: TFontDC;
  out Face: RawByteString): boolean;
var
  ttc, dir: RawByteString;
  len: cardinal;
  index: integer;
begin
  // a face of a .ttc: GetFontData(0) returns its table directory with offsets
  // into the collection, so the face is found in and extracted from the
  // whole collection ('ttcf')
  result := false;
  if Windows.GetFontData(HDC(DC), TTCF_TABLE, 0, nil, 0) = GDI_ERROR then
  begin
    result := ReadFontData(HDC(DC), 0, Face); // a font file of one face
    exit;
  end;
  if not ReadFontData(HDC(DC), TTCF_TABLE, ttc) then
    exit; // a collection, but unreadable: never its raw face
  // only the table directory of the face, as TtcFaceIndex compares it
  FastSetRawByteString(dir, nil, 12);
  if Windows.GetFontData(HDC(DC), 0, 0, pointer(dir), 12) <> 12 then
    exit;
  len := 12 + 16 * ((cardinal(ord(dir[5])) shl 8) or cardinal(ord(dir[6])));
  FastSetRawByteString(dir, nil, len);
  if Windows.GetFontData(HDC(DC), 0, 0, pointer(dir), len) <> len then
    exit;
  index := TtcFaceIndex(ttc, dir);
  if index < 0 then
    exit;
  Face := ExtractSfntFromTtc(ttc, index);
  result := Face <> '';
end;

{ TGdiFontEnumerator }

type
  PRawUtf8DynArray = ^TRawUtf8DynArray;

// EnumFontFamiliesExW callback - FPC wants ENUMLOGFONTEXW / NEWTEXTMETRICEXW
function EnumFontsProcW(var LogFont: ENUMLOGFONTEXW;
  var TextMetric: NEWTEXTMETRICEXW;
  FontType: integer; lParam: LPARAM): integer; stdcall;
var
  u: RawUtf8;
begin
  with LogFont.elfLogFont do
    if ((FontType = DEVICE_FONTTYPE) or
        (FontType = TRUETYPE_FONTTYPE)) and
       (lfFaceName[0] <> '@') then
    begin
      RawUnicodeToUtf8(@lfFaceName[0], StrLenW(@lfFaceName[0]), u);
      AddRawUtf8(PRawUtf8DynArray(PtrUInt(lParam))^, u, true, true);
    end;
  result := 1; // continue enumeration
end;

procedure TGdiFontEnumerator.EnumTrueTypeFonts(DC: TFontDC;
  var List: TRawUtf8DynArray);
var
  LFont: TLogFontW;
begin
  FillChar(LFont, SizeOf(LFont), 0);
  LFont.lfCharSet := DEFAULT_CHARSET; // enumerate ALL fonts
  EnumFontFamiliesExW(HDC(DC), LFont, @EnumFontsProcW, LPARAM(@List), 0);
end;

{ TGdiFontDC }

function TGdiFontDC.CreateDC: TFontDC;
begin
  result := TFontDC(Windows.CreateCompatibleDC(0));
end;

procedure TGdiFontDC.DeleteDC(DC: TFontDC);
begin
  if DC <> nil then
    Windows.DeleteDC(HDC(DC));
end;

function TGdiFontDC.GetScreenLogPixels(DC: TFontDC): integer;
begin
  result := GetDeviceCaps(HDC(DC), LOGPIXELSY);
end;


{ ****************** Uniscribe Shaper and FontSub Subsetter: IFontShaper and IFontSubsetter }

{ TUniscribeShaper }

function TUniscribeShaper.Shape(Text: PWideChar; Len: integer;
  Font: TFontHandle; RightToLeft: boolean; out Runs: TFontShapedRuns): boolean;
var
  i, j, n, L, max, maxglyphs, count, numSp, glyphsCount: integer;
  res: HRESULT;
  Sp: PScriptPropertiesArray;
  items: array of TScriptItem;
  level: array of byte;
  VisualToLogical: array of integer;
  psc: pointer; // opaque Uniscribe font metric cache
  complex, R2L: boolean;
  attrs: array of TScriptVisAttr;
  glyphs, logclust: array of word;
  control: TScriptControl;
  state: TScriptState;
  dc: HDC;
  old: HGDIOBJ;

  procedure AddRun(Kind: TFontShapeKind; Outcome: TFontShapeOutcome);
  begin
    SetLength(Runs, n + 1);
    Runs[n].Kind := Kind;
    Runs[n].Outcome := Outcome;
    Runs[n].TextStart := items[i].iCharPos;
    Runs[n].TextLen := L;
    inc(n);
  end;

  procedure AddShaped;
  var
    g, k: integer;
  begin
    if glyphsCount = 0 then
    begin
      AddRun(fskSkip, fsoDone); // nothing to draw
      exit;
    end;
    AddRun(fskShaped, fsoDone);
    SetLength(Runs[n - 1].Glyphs, glyphsCount);
    k := 0;
    for g := 0 to glyphsCount - 1 do
      // a zero-width glyph which is no diacritic draws nothing
      if attrs[g].fFlags * [fDiacritic, fZeroWidth] <> [fZeroWidth] then
      begin
        Runs[n - 1].Glyphs[k] := glyphs[g];
        inc(k);
      end;
    SetLength(Runs[n - 1].Glyphs, k);
  end;

begin
  result := false;
  Runs := nil;
  if (Text = nil) or
     (Len <= 0) or
     (Font = nil) then
    exit;
  // 1. break the text into individually shapeable items
  max := Len + 3;
  SetLength(items, max + 1); // ScriptItemize adds a terminal item
  count := 0;
  FillCharFast(control, SizeOf(control), 0);
  FillCharFast(state, SizeOf(state), 0);
  if ScriptApplyDigitSubstitution(nil, @control, @state) <> 0 then
    exit;
  if RightToLeft then
    state.uBidiLevel := 1;
  if (ScriptItemize(Text, Len, max, @control, @state,
       pointer(items), count) <> 0) or
     (count <= 0) then
    exit;
  // 2. leave the text to the caller unless an item needs shaping or layout
  ScriptGetProperties(Sp, numSp);
  complex := false;
  R2L := false;
  for i := 0 to count - 1 do
    if fComplex in Sp^[items[i].a.eScript and (1 shl 10 - 1)]^.fFlags then
      complex := true
    else if fRtl in items[i].a.fFlags then
      R2L := true;
  if not complex and
     not R2L then
    exit;
  // 3. the visual order of the items
  SetLength(level, count);
  for i := 0 to count - 1 do
    level[i] := items[i].a.s.uBidiLevel;
  SetLength(VisualToLogical, count);
  if ScriptLayout(count, pointer(level), pointer(VisualToLogical), nil) <> 0 then
    exit;
  // 4. shape every item; one buffer size for all, as large as the whole text
  // with its terminating #0 needs
  maxglyphs := ((Len + 1) * 3) shr 1 + 32;
  SetLength(attrs, maxglyphs);
  SetLength(glyphs, maxglyphs);
  SetLength(logclust, maxglyphs);
  psc := nil; // cached for the same font
  dc := 0;
  old := 0;
  n := 0;
  try
    for j := 0 to count - 1 do
    begin
      i := VisualToLogical[j];
      L := items[i + 1].iCharPos - items[i].iCharPos;
      if L <= 0 then
        continue; // covers no code unit
      res := ScriptShape(0, psc, Text + items[i].iCharPos, L, maxglyphs,
        @items[i].a, pointer(glyphs), pointer(logclust), pointer(attrs),
        glyphsCount);
      case res of
        0:
          AddShaped;
        E_OUTOFMEMORY:
          AddRun(fskPlain, fsoFailed); // maxglyphs too small
        E_PENDING,
        USP_E_SCRIPT_NOT_IN_FONT:
          begin
            // the font has to be selected into a DC
            if dc = 0 then
            begin
              dc := CreateCompatibleDC(0);
              old := SelectObject(dc, HGDIOBJ(Font));
            end;
            res := ScriptShape(dc, psc, Text + items[i].iCharPos, L, maxglyphs,
              @items[i].a, pointer(glyphs), pointer(logclust), pointer(attrs),
              glyphsCount);
            if res = 0 then
              AddShaped
            else
              // the script is not in this font: no font of its own is chosen
              // here, see https://learn.microsoft.com/windows/win32/intl/
              // displaying-text-with-uniscribe
              AddRun(fskPlain, fsoFailed);
          end;
      else
        AddRun(fskSkip, fsoFailed);
      end;
    end;
  finally
    if dc <> 0 then
    begin
      SelectObject(dc, old);
      DeleteDC(dc);
    end;
    if psc <> nil then
      ScriptFreeCache(psc);
  end;
  result := true;
end;


{ TFontSubSubsetter }

const
  /// GetGlyphIndicesW() flag: unmapped code points come back as $ffff
  // - without it they resolve to glyph 0, which would keep .notdef for them
  GGI_MARK_NONEXISTING_GLYPHS = 1;

// not declared by the FPC windows unit nor by Delphi 7
function GetGlyphIndicesW(DC: HDC; Str: PWideChar; Count: integer;
  Glyphs: PWord; Flags: cardinal): cardinal; stdcall;
  external 'gdi32.dll' name 'GetGlyphIndicesW';

type
  TTtfTableDirectory = packed record
    sfntVersion: cardinal; // 0x00010000 for version 1.0
    numTables: word;       // number of tables
    searchRange: word;     // HighBit(NumTables) x 16
    entrySelector: word;   // Log2(HighBit(NumTables))
    rangeShift: word;      // NumTables x 16 - SearchRange
  end;
  PTtfTableDirectory = ^TTtfTableDirectory;

  TTtfTableEntry = packed record
    tag: cardinal;      // table identifier
    checksum: cardinal; // checksum for this table
    offset: cardinal;   // offset from start of font file
    length: cardinal;   // length of this table
  end;
  PTtfTableEntry = ^TTtfTableEntry;

const
  // see http://www.4real.gr/technical-documents-ttf-subset.html and
  // https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6.html
  TTF_SUBSET: array[0..9] of array[0..3] of AnsiChar = (
    'head', 'cvt ', 'fpgm', 'prep', 'hhea', 'maxp', 'hmtx', 'cmap', 'loca', 'glyf');
  HEAD_TABLE = $64616568; // 'head'

procedure ReduceTtf(out Ttf: RawByteString; SubsetData: pointer;
  SubsetSize: integer);
var
  dir: PTtfTableDirectory;
  d, e: PTtfTableEntry;
  head: PAnsiChar;
  n, i, len: PtrInt;
  checksum: cardinal;
begin
  Ttf := ''; // an out parameter: no former content to keep
  SetLength(Ttf, SubsetSize); // maximum size
  d := pointer(Ttf);
  inc(PTtfTableDirectory(d));
  // identify the tables to be included
  e := SubsetData;
  inc(PTtfTableDirectory(e));
  n := 0;
  if SubsetSize > SizeOf(PTtfTableDirectory) then
    for i := 1 to bswap16(PTtfTableDirectory(SubsetData)^.numTables) do
    begin
      if IntegerScanIndex(@TTF_SUBSET, length(TTF_SUBSET), e^.tag) >= 0 then
      begin
        d^ := e^;
        inc(d);
        inc(n);
      end;
      inc(e);
    end;
  if n < 8 then // pdf expects 10 tables, and 8..15 for our fixed dir^ values
  begin
    MoveFast(SubsetData^, pointer(Ttf)^, SubsetSize); // paranoid
    exit;
  end;
  // update the main directory
  dir := pointer(Ttf);
  dir^.sfntVersion := PTtfTableDirectory(SubsetData)^.sfntVersion;
  dir^.numTables := bswap16(n);
  dir^.searchRange := 32768; // pre-computed values for n in 8..15
  dir^.entrySelector := 768;
  dir^.rangeShift := 8192;
  // include the associated data
  checksum := 0;
  head := nil;
  e := pointer(Ttf);
  inc(PTtfTableDirectory(e));
  for i := 1 to n do
  begin
    len := bswap32(e^.length);
    MoveFast(PByteArray(SubsetData)[bswap32(e^.offset)], d^, len);
    e^.offset := bswap32(PtrUInt(d) - PtrUInt(Ttf));
    if e^.tag = HEAD_TABLE then
      head := pointer(d);
    while len and 3 <> 0 do
    begin // 32-bit padding
      PByteArray(d)[len] := 0;
      inc(len);
    end;
    inc(checksum, bswap32(e^.checksum)); // we didn't change the table itself
    inc(PByte(d), len);
    inc(e);
  end;
  // finalize the generated content
  for i := 0 to ((SizeOf(dir^) + (n * SizeOf(e^))) shr 2) - 1 do
    inc(checksum, PCardinalArray(Ttf)[i]);
  if head <> nil then // head.checkSumAdjustment is at offset 8
    PCardinal(head + 8)^ := bswap32($B1B0AFBA - checksum);
  SetLength(Ttf, PtrUInt(d) - PtrUInt(Ttf));
end;

function TFontSubSubsetter.Subset(const Face: RawByteString;
  const Request: TFontSubsetRequest; Font: TFontHandle;
  out Output: RawByteString): boolean;
var
  dc: HDC;
  old: HGDIOBJ;
  keep: TSortedWordArray;
  data: RawByteString;
  size, submem, subsize: cardinal;
  subdata: PAnsiChar;
  flags, index: word;
  idx: integer;
  wide: array of WideChar;
  gid: array of word;
  i, n: PtrInt;
  c: integer;
begin
  result := false;
  Output := '';
  if (Font = nil) or
     (Face = '') or
     not HasCreateFontPackage then
    exit;
  // the keep list has to be sorted and free of duplicates
  keep.Count := 0;
  for i := 0 to high(Request.Glyphs) do
    keep.Add(Request.Glyphs[i]);
  dc := CreateCompatibleDC(0);
  if dc = 0 then
    exit;
  old := SelectObject(dc, HGDIOBJ(Font));
  try
    // the code points through the cmap of the font, as GDI maps them
    SetLength(wide, length(Request.Unicodes));
    n := 0;
    for i := 0 to high(Request.Unicodes) do
    begin
      c := Request.Unicodes[i];
      if (c > 0) and
         (c <= $ffff) and
         ((c < $d800) or (c > $dfff)) then
      begin
        wide[n] := WideChar(c);
        inc(n);
      end;
    end;
    if n > 0 then
    begin
      SetLength(gid, n);
      if GetGlyphIndicesW(dc, pointer(wide), n, pointer(gid),
           GGI_MARK_NONEXISTING_GLYPHS) <> GDI_ERROR then
        for i := 0 to n - 1 do
          if gid[i] <> $ffff then // not in this face: nothing to keep
            keep.Add(gid[i]);
    end;
    if keep.Count = 0 then
      exit;
    // a face of a .ttc collection: CreateFontPackage wants the collection
    size := Windows.GetFontData(dc, TTCF_TABLE, 0, nil, 0);
    if size <> GDI_ERROR then
    begin
      SetLength(data, size);
      if Windows.GetFontData(dc, TTCF_TABLE, 0, pointer(data), size) <> size then
        exit;
      idx := TtcFaceIndex(data, Face);
      if idx < 0 then
        exit; // no reliable index: not subset, and GetFaceFile fails too
      flags := TTFCFP_FLAGS_SUBSET or TTFCFP_FLAGS_TTC;
      index := idx;
    end
    else
    begin
      data := Face;
      flags := TTFCFP_FLAGS_SUBSET;
      index := 0;
    end;
  finally
    SelectObject(dc, old);
    DeleteDC(dc);
  end;
  if CreateFontPackage(pointer(data), length(data), subdata, submem, subsize,
       flags or TTFCFP_FLAGS_GLYPHLIST, index, TTFMFP_SUBSET, 0,
       TTFCFP_MS_PLATFORMID, TTFCFP_DONT_CARE, pointer(keep.Values),
       keep.Count, @lpfnAllocate, @lpfnReAllocate, @lpfnFree, nil) <> 0 then
    exit;
  try
    ReduceTtf(Output, subdata, subsize);
  finally
    FreeMem(subdata);
  end;
  result := Output <> '';
end;

function TFontSubSubsetter.SupportsSymbolic: boolean;
begin
  result := true; // GetGlyphIndicesW maps the WinAnsi bytes of a symbol font
end;


var
  RegisteredShaper: IFontShaper;
  RegisteredSubsetter: IFontSubsetter;

procedure RegisterUniscribe;
begin
  RegisterFontPlatform(
    TGdiFontProvider.Create,
    TGdiFontEnumerator.Create,
    TGdiFontDC.Create);
  {$ifndef NO_USE_UNISCRIBE} // set project-wide: no shaping, no subsetting
  RegisteredShaper := TUniscribeShaper.Create;
  FontShaper := RegisteredShaper;
  if HasCreateFontPackage then
  begin
    RegisteredSubsetter := TFontSubSubsetter.Create;
    FontSubsetter := RegisteredSubsetter;
  end;
  {$endif NO_USE_UNISCRIBE}
end;

procedure UnregisterUniscribe;
begin
  // release the services before the library they call
  if FontShaper = RegisteredShaper then
    FontShaper := nil;
  if FontSubsetter = RegisteredSubsetter then
    FontSubsetter := nil;
  RegisteredShaper := nil;
  RegisteredSubsetter := nil;
  if (FontSub <> 0) and
     (FontSub <> INVALID_HANDLE_VALUE) then
    FreeLibrary(FontSub);
end;


initialization
  RegisterUniscribe;

finalization
  UnregisterUniscribe;

{$endif OSPOSIX}


end.

